# Model validation and Classification

## The different machine learning types

![](images/machine_learning_types_tree.png)

### No matter what type of machine learning we need to create a good model

# Data models
### How to make good models
- Find representative data. Data that is a subset of reality but as far as possible represents all aspects of reality properly distributed.
- Split data into a **training** part 2/3 to 4/5 of the data and a **test** part of the data
- Train the model with the training data over multiple iterations
- Test the model with the test data, to see how well the model performs on unknown data.

## Your model versus the population

A sample is a **subset** of a population.

You will likely **never** have data that covers the entire population.

That means that you will likely **never** be able to represent the entire population!

Your model will lie!

## Populations

![](images/pop1.png)

## The problem of overfitting
Occam's razor implies that any given complex function is a priori less probable than any given simple function. If the new, more complicated function is selected instead of the simple function, and if there was not a large enough gain in training-data fit to offset the complexity increase, then the new complex function "overfits" the data, and the complex overfitted function will likely perform worse than the simpler function on validation data outside the training dataset, even though the complex function performed as well, or perhaps even better, on the training dataset

![](images/overfitting.png)

#### The smaller the dataset the more risk of overfitting
For neural networks, using a small network is one way to mitigate overfitting.


## Carowners and voters

In 1963 *millions* of mock ballots was mailed to carowners across the USA, to learn who would win the presidential election.

The Republicans was a *clear* winner in the mock ballots, but the Democrats won the election.

What went wrong?

## The problem of generalisation

If X % of sample has Y it does **not** mean that X % of population has Y!

**Always** ask yourself: is your data representative?

## Training and testing data

We now have a split between 
* **Training data**: the data that the model sees
* **Testing data**: the data that the model is tested against

Note: the model should **never** train on the testing data

## Sklearn `train_test_split`

Splitting the data into testing and training makes it more likely that your model generalises.

But it **does not guarantee it**!

In [1]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [2]:
from sklearn.datasets import load_iris

In [3]:
X = load_iris().data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y = load_iris().target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
load_iris().target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
from sklearn.model_selection import train_test_split
train_test_split(X, y)

[array([[5. , 3.2, 1.2, 0.2],
        [5.7, 2.6, 3.5, 1. ],
        [6.3, 2.9, 5.6, 1.8],
        [5.4, 3.9, 1.7, 0.4],
        [4.8, 3.4, 1.6, 0.2],
        [7.2, 3. , 5.8, 1.6],
        [4.9, 3.6, 1.4, 0.1],
        [5. , 3.5, 1.6, 0.6],
        [6.2, 2.9, 4.3, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [4.8, 3. , 1.4, 0.1],
        [6.4, 2.7, 5.3, 1.9],
        [6.2, 2.2, 4.5, 1.5],
        [6.7, 3.3, 5.7, 2.1],
        [6.5, 3.2, 5.1, 2. ],
        [6.1, 2.8, 4.7, 1.2],
        [6.7, 3.1, 4.4, 1.4],
        [4.3, 3. , 1.1, 0.1],
        [5.5, 3.5, 1.3, 0.2],
        [6.2, 3.4, 5.4, 2.3],
        [6.5, 3. , 5.2, 2. ],
        [5.9, 3.2, 4.8, 1.8],
        [6. , 2.7, 5.1, 1.6],
        [5.6, 3. , 4.1, 1.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.4, 1.4, 0.3],
        [6.7, 3.1, 4.7, 1.5],
        [5.7, 3. , 4.2, 1.2],
        [6.4, 3.2, 5.3, 2.3],
        [6.1, 2.9, 4.7, 1.4],
        [5. , 3.6, 1.4, 0.2],
        [5.7, 2.9, 4.2, 1.3],
        [4

In [7]:
# split the data into training data (2/3) for x and for y and test data (1/3) for x and for y
# training data is for the model to learn, test data to see if the model learned correctly
x_train, x_test, y_train, y_test = train_test_split(X, y)
print(y_train)

[2 2 1 2 0 1 1 2 1 0 0 1 2 0 2 0 0 0 2 1 1 1 0 2 2 0 0 2 2 2 0 2 0 2 0 2 1
 1 1 0 2 1 1 1 0 0 1 0 1 2 0 1 2 1 2 0 1 1 2 0 0 2 0 2 2 2 2 2 1 0 1 0 1 1
 0 1 0 0 1 0 1 0 1 0 1 0 0 0 2 1 0 1 0 0 2 0 2 1 2 2 1 2 2 1 2 2 2 2 1 2 2
 0]


In [8]:
# use the linear regression model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [9]:
targets = model.predict(x_train)
targets

array([ 1.53138760e+00,  1.71527169e+00,  8.78267777e-01,  1.90372309e+00,
       -2.27173296e-02,  1.18655966e+00,  1.07112930e+00,  1.94892224e+00,
        1.41311683e+00,  1.91060731e-01,  3.29439713e-02,  1.16749412e+00,
        1.84384744e+00,  8.67675924e-02,  1.81138102e+00, -2.19507525e-03,
       -5.20001390e-02, -6.10974808e-02,  1.78695321e+00,  1.29146396e+00,
        1.33168820e+00,  1.19255839e+00, -1.24160936e-01,  1.99787483e+00,
        2.26519573e+00, -5.41213115e-02, -4.94873938e-02,  1.98529421e+00,
        1.88287737e+00,  1.75361964e+00, -7.37447127e-02,  2.03134669e+00,
       -9.03936399e-03,  1.58384641e+00, -8.53015058e-02,  1.84459690e+00,
        1.31884518e+00,  1.21703950e+00,  1.05518767e+00, -7.76755637e-02,
        2.12001389e+00,  1.15911453e+00,  1.21436046e+00,  9.31441625e-01,
       -5.23622184e-02,  9.82123607e-04,  1.30589558e+00, -1.21897271e-01,
        1.16908272e+00,  1.49074379e+00, -2.60370209e-02,  1.27055433e+00,
        1.65477428e+00,  

In [10]:
model.score(x_train, y_train)

0.9317399520006568

In [11]:
model.score(x_test, y_test)

0.9215267042234505

## Evaluating a model

* Models are supposed to be as accurate as possible
  * `model.score`
  * Read the [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html#sklearn.linear_model.LinearRegression.score)

* But not *too* accurate
  * Overfitting

## The overfitting curve
[Overfitting](https://en.wikipedia.org/wiki/Overfitting)  

Curve shows number of training cycles on the x-axis and on y-axis how blue and red (training error, validation error) enlarges at a point. This point is where validation error has its global minimum. That is when we need to **stop** training the model with the training data.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Overfitting_svg.svg/1280px-Overfitting_svg.svg.png" style="width:40%"/>

## Exercise

* Import `science.csv` to a pandas DataFrame
* Split the input (X) and target (y) using `train_test_split`
* Train the model on the training data
* Score the model based on the testing data

## Self study: Other sklearn metrics

The model uses *default* metrics. But there are numerous others.

https://sklearn.org/modules/classes.html#module-sklearn.metrics

Metrics usually depends on the type of your model (classification, regression, etc.)

Read this article [here](https://towardsdatascience.com/understanding-data-science-classification-metrics-in-scikit-learn-in-python-3bc336865019)

In [12]:
import sklearn
sklearn.metrics.SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_s